name: Xiaozhi Gateway
version: "0.1.0"
slug: xiaozhi_gateway
description: Xiaozhi Home Assistant gateway
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ports:
  8125/tcp: 8125
map:
  - type: addon_config
    read_only: false
options:
  piper_host: core-piper
  piper_port: 10200
  devices:
    - key: living_room_xiaozhi
      device_id: "aa:bb:cc:dd:ee:ff"
      client_id: livingroom_xiaozhi
      room_id: living_room
      room_name: 客厅
      ha_area_id: living_room
      ha_device_id: ""
schema:
  piper_host: str
  piper_port: int
  devices:
    - key: str
      device_id: str
      client_id: str?
      room_id: str
      room_name: str
      ha_area_id: str
      ha_device_id: str?
